### ISSUE TITLE
Error when using path without a slash

### ISSUE THREAD

**Issue by ttill** [michaljach/ember-cli-deploy-scp#15]
Because of the way the `parentPath` is constructed in `DeployPlugin.upload`, using a path config like `production`, which refers to the production folder in the user's home, leads to an unspecific rsync error.

**Comment by michaljach** [comment]
Hi, could You give some more details or maybe example with folder structure ?

**Comment by ttill** [comment]
The following is correctly handled by scp:
```javascript
ENV['scp'] = {
    username: 'user',
    host: 'host.com',
    path: 'path_to_ember'
};
```
It refers to the folder `/home/user/path_to_ember`. But because of the way the parent path is constructed in  `DeployPlugin.upload()` I have to write:

**Comment by gabrielgrant** [comment]
Just ran into this too. The error is pretty opaque: 

```
$ ember deploy production
WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.
cleaning up...
Deploying [====>] 100% [plugin: scp -> upload]
- Error: rsync exited with code 11
Error: rsync exited with code 11
Error: rsync exited with code 11
    at Rsync.<anonymous> (/path/to/my/app/node_modules/rsync/rsync.js:470:21)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:606:12)Pipeline aborted
```
